from django.db import models

class Employee(models.Model):
    employee_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    title_id = models.TextField()
    team_id = models.TextField()
    role_id = models.TextField()
    start_date = models.CharField(max_length=50)
    employment_end_date = models.CharField(max_length=50, null=True, blank=True)
    review_type = models.CharField(max_length=255)
    early_review_reminder_date = models.CharField(max_length=50, null=True, blank=True)
    review_date = models.CharField(max_length=50, null=True, blank=True)
    review_schedule_date = models.CharField(max_length=50, null=True, blank=True)
    review_completed = models.CharField(max_length=2, null=True, blank=True)
    review_notes = models.TextField(null=True, blank=True)
    review_document = models.TextField(null=True, blank=True)
    employment_status = models.CharField(max_length=255)
    supervising_provider_employee = models.TextField(null=True, blank=True)
    supervision_start_date = models.CharField(max_length=50, null=True, blank=True)
    supervision_notes = models.TextField(null=True, blank=True)
    work_email = models.TextField()
    personal_email = models.TextField()
    employment_type = models.CharField(max_length=255)
    weekly_hours_commitment = models.CharField(max_length=100, null=True, blank=True)
    employment_hours_notes = models.TextField(null=True, blank=True)
    pay_unit = models.CharField(max_length=255)
    current_salary = models.CharField(max_length=100)
    physical_location = models.TextField(null=True, blank=True)
    timezone_id = models.TextField(null=True, blank=True)
    contact_number = models.TextField(null=True, blank=True)
    referral_id = models.TextField(null=True, blank=True)
    increased_salary = models.TextField(null=True, blank=True)
    increased_salary_effective_date = models.CharField(max_length=50, null=True, blank=True)
    emergency_contact_name = models.TextField(null=True, blank=True)
    headshot = models.TextField(null=True, blank=True)
    birthday = models.CharField(max_length=50, null=True, blank=True)
    appsheet_id = models.TextField(null=True, blank=True)
    spouse_birthday = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"