# Generated by Django 5.0.6 on 2024-06-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('title_id', models.TextField()),
                ('team_id', models.TextField()),
                ('role_id', models.TextField()),
                ('start_date', models.CharField(max_length=50)),
                ('employment_end_date', models.CharField(blank=True, max_length=50, null=True)),
                ('review_type', models.CharField(max_length=255)),
                ('early_review_reminder_date', models.CharField(blank=True, max_length=50, null=True)),
                ('review_date', models.CharField(blank=True, max_length=50, null=True)),
                ('review_schedule_date', models.CharField(blank=True, max_length=50, null=True)),
                ('review_completed', models.CharField(blank=True, max_length=2, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('review_document', models.TextField(blank=True, null=True)),
                ('employment_status', models.CharField(max_length=255)),
                ('supervising_provider_employee', models.TextField(blank=True, null=True)),
                ('supervision_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('supervision_notes', models.TextField(blank=True, null=True)),
                ('work_email', models.TextField()),
                ('personal_email', models.TextField()),
                ('employment_type', models.CharField(max_length=255)),
                ('weekly_hours_commitment', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_hours_notes', models.TextField(blank=True, null=True)),
                ('pay_unit', models.CharField(max_length=255)),
                ('current_salary', models.CharField(max_length=100)),
                ('physical_location', models.TextField(blank=True, null=True)),
                ('timezone_id', models.TextField(blank=True, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('referral_id', models.TextField(blank=True, null=True)),
                ('increased_salary', models.TextField(blank=True, null=True)),
                ('increased_salary_effective_date', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_name', models.TextField(blank=True, null=True)),
                ('headshot', models.TextField(blank=True, null=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('appsheet_id', models.TextField(blank=True, null=True)),
                ('spouse_birthday', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
